version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mandry

  app:
    build: .
    entrypoint: ["/entrypoint.sh"]
    env_file:
      - .env
    command: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    networks:
      - mandry

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - APP_PORT=${APP_PORT}
    depends_on:
     - app
     - db
    networks:
      - mandry

networks:
  mandry:

volumes:
  db_data:
