version: '3'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - news_aggregator

  app:
    build: .
    env_file:
      - .env
    command: ./entrypoint.sh
    volumes:
      - .:/code
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      - db
    networks:
      - news_aggregator

networks:
  news_aggregator:

volumes:
  db_data:
