version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=proj_db
      - POSTGRES_USER=proj_usr
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - mandry

  app:
    build: .
    env_file:
      - .env
    volumes:
      - .:/usr/src
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - mandry

networks:
  mandry:

volumes:
  db_data:
