# Generated by Django 4.2.5 on 2023-10-05 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0002_trip_created_at_trip_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='passangers',
            field=models.ManyToManyField(blank=True, null=True, related_name='trip_passangers', to=settings.AUTH_USER_MODEL),
        ),
    ]
