# Generated by Django 4.2.5 on 2023-11-10 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0004_alter_trip_passangers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='name',
        ),
        migrations.AddField(
            model_name='trip',
            name='destination',
            field=models.CharField(default='Destination', max_length=70),
        ),
        migrations.AddField(
            model_name='trip',
            name='title',
            field=models.CharField(default='Trip', max_length=35),
        ),
    ]
