# Generated by Django 4.2.5 on 2023-11-26 16:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trip', '0005_remove_trip_name_trip_destination_trip_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='max_passangers',
            new_name='max_passengers',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='passangers',
        ),
        migrations.AddField(
            model_name='trip',
            name='passengers',
            field=models.ManyToManyField(blank=True, related_name='joined_trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
