# Generated by Django 4.2.5 on 2023-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0006_rename_max_passangers_trip_max_passengers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('middle', 'Middle'), ('hard', 'Hard')], default='easy', max_length=6),
        ),
    ]
