# Generated by Django 4.2.5 on 2023-12-09 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='difficulty',
        ),
    ]
