# Generated by Django 4.2.5 on 2023-12-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0009_remove_trip_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('middle', 'Middle'), ('hard', 'Hard')], default='easy', max_length=6),
        ),
    ]
