# Generated by Django 4.2.5 on 2023-12-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0011_tripimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='max_passengers',
            field=models.IntegerField(),
        ),
    ]
