# Generated by Django 4.2.5 on 2023-09-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0002_alter_traveller_email_alter_traveller_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveller',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
