# Generated by Django 4.2.5 on 2023-10-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0003_traveller_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='Comment example'),
        ),
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='image',
            field=models.FileField(default='profile_images/default-image.jpg', upload_to='profile_images/'),
        ),
    ]
