# Generated by Django 4.2.5 on 2023-10-05 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0004_comment_comment_comment_rating_alter_traveller_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveller',
            name='rating',
        ),
        migrations.AlterField(
            model_name='traveller',
            name='last_name',
            field=models.CharField(max_length=35, verbose_name='last_name'),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='phone_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
