# Generated by Django 4.2.5 on 2023-12-09 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveller', '0006_alter_traveller_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='traveller',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(12)]),
        ),
    ]
