name: CI

on:
  push:
    branches:
      - main
      - web-development
      - AI-development
  pull_request:
    branches:
      - main
      - web-development
      - AI-development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install flake8
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Run flake8
        run: flake8 .
