name: Continuous Integration and Deployment

on:
  push:
    branches:
      - main
      - web-development
      - AI-development
  pull_request:
    branches:
      - main
      - web-development
      - AI-development
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 .

      # - name: Build Docker image
      #   run: docker build -t mandry-app .

      # - name: Run Docker container
      #   run: docker run -d -p 8000:8000 mandry-app

      # - name: Run tests
      #   run: |
      #     # Add commands to run your tests here, for example:
      #     # python manage.py test

